### ISSUE TITLE
rechnung init broken

### ISSUE THREAD

**Issue by aparcar** [westnetz/rechnung#12]
```
a@tb:~/src/rechnung/test$ rechnung init
Initializing...
Traceback (most recent call last):
  File "/home/a/.local/bin/rechnung", line 11, in <module>
    load_entry_point('rechnung', 'console_scripts', 'rechnung')()
  File "/home/a/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/a/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/a/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/a/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/a/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/a/src/rechnung/rechnung/cli.py", line 28, in init
    settings = get_settings_from_cwd(cwd, create_non_existing_dirs=True)
  File "/home/a/src/rechnung/rechnung/settings.py", line 81, in get_settings_from_cwd
    Path(cwd) / settings_file, create_non_existing_dirs=create_non_existing_dirs
  File "/home/a/src/rechnung/rechnung/settings.py", line 126, in get_settings_from_file
    s_value = base_path / settings_data["assets_dir"] / s_value
  File "/usr/lib/python3.7/pathlib.py", line 908, in __truediv__
    return self._make_child((key,))
  File "/usr/lib/python3.7/pathlib.py", line 695, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.7/pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by olf42** [comment]
Is fixed in https://github.com/westnetz/rechnung/pull/15
